apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xarr.fullname" . }}
  labels:
    {{- include "xarr.labels" . | nindent 4 }}
spec:
  #replicas: {{ .Values.replicaCount }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "xarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xarr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: app
              containerPort: {{ .Values.appPort }}
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #  initialDelaySecynds: {{ .Values.probes.livenessProbe.initialDelaySeconds }}
          #  timeoutSeconds: {{ .Values.probes.livenessProbe.timeoutSeconds }}
          #  periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds }}
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #  initialDelaySecynds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
          #  timeoutSeconds: {{ .Values.probes.readinessProbe.timeoutSeconds }}
          #  periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
          #startupProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #  initialDelaySecynds: {{ .Values.probes.startupProbe.initialDelaySeconds }}
          #  timeoutSeconds: {{ .Values.probes.startupProbe.timeoutSeconds }}
          #  periodSeconds: {{ .Values.probes.startupProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: /{{ .Chart.Name }}
            - name: data
              mountPath: /data
      initContainers:
        - name: init-{{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - sh
          - -c
          - |
            set -eo pipefail
            [[ $DEBUG ]] && set -x
            app_config=/shared-config/${CONFIG_SUBPATH}
            mkdir -p $app_config
            [[ -f ${app_config}/config.xml ]] || \
              cp /chart-config/config.xml $app_config
          env:
          - name: APP
            value: "{{ .Chart.Name }}"
          - name: CONFIG_SUBPATH
            value: "{{ .Chart.Name }}"
          - name: DEBUG
            value: {{ .Values.debug.enabled | ternary "yes" "" }}
          volumeMounts:
            - name: config
              mountPath: /shared-config
            - name: chart-config
              mountPath: /chart-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: chart-config
          configMap:
            name: {{ include "xarr.fullname" . }}
        - name: config
          persistentVolumeClaim:
            claimName: "{{ .Values.volumes.config.pvcName | default .Values.global.volumes.config.pvcName }}"
        - name: data
          nfs:
            server: "{{ .Values.volumes.data.nfsServer | default .Values.global.volumes.data.nfsServer }}"
            path: "{{ .Values.volumes.data.nfsPath | default .Values.global.volumes.data.nfsPath }}"
