global:
  volumes:
    config:
      nfsServer: nas.example.com
      nfsPath: /media/config
      #pvcName: config
      #storageClassName: openebs-jiva-csi-default
      #size: 4Gi
    data:
      nfsServer: nas.example.com
      nfsPath: /media
  ingress:
    host: &mediahost mymedia.example.com


sonarr:
  deploy: true
  appPort: 8989
  ingress:
    enabled: true
    hosts:
      - host: *mediahost
        paths:
          - path: sonarr/
  image:
    repository: linuxserver/sonarr
    tag: arm64v8-latest
radarr:
  deploy: false
  appPort: 7878
  ingress:
    enabled: true
    hosts:
      - host: *mediahost
        paths:
          - path: radarr/
  image:
    repository: linuxserver/radarr
    tag: arm64v8-latest
nzbget:
  deploy: false
  appPort: 6789
  ingress:
    enabled: true
    hosts:
      - host: *mediahost
        paths:
          - path: nzbget/
  image:
    repository: linuxserver/nzbget
    tag: arm64v8-latest
bazarr:
  deploy: false
  appPort: 6767
  ingress:
    enabled: true
    hosts:
      - host: *mediahost
        paths:
          - path: bazarr/
  image:
    repository: linuxserver/bazarr
    tag: arm64v8-latest
plex:
  deploy: false
  appPort: 32400
  ingress:
    enabled: true
    hosts:
      - host: *mediahost
        paths:
          - path: plex/
  image:
    repository: linuxserver/plex
    tag: arm64v8-latest
