apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ required "Config PVC Name Required - global.volumes.config.pvcName " .Values.global.volumes.config.pvcName }}
spec:
  storageClassName: {{ required "Config PVC StorageClass Required - global.volumes.config.storageClassName" .Values.global.volumes.config.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ required "Config PVC Size Required - global.volumes.config.size" .Values.global.volumes.config.size }}